import assert from "node:assert/strict";
import test from "node:test";

import { buildTeamAgentInstructions } from "../../lib/team-mode/agent-instructions.ts";

test("hosted agent instructions are origin-bound and cover both marketplace roles", () => {
  const markdown = buildTeamAgentInstructions("https://ads.example.com");
  assert.match(markdown, /^# Ad Daddy/m);
  assert.match(markdown, /https:\/\/ads\.example\.com\/api\/team/);
  assert.match(markdown, /join/);
  assert.match(markdown, /invite code/i);
  assert.match(markdown, /may paste.*invite code.*conversation/i);
  assert.match(markdown, /--invite-code '<INVITE_CODE>'/);
  assert.match(markdown, /--input -/);
  assert.match(markdown, /send those bytes through stdin/i);
  assert.match(markdown, /never interpolate a human-provided name or profile value into a shell command/i);
  const joinSnippet = markdown.match(/ad-daddy team join[\s\S]*?```/)?.[0] ?? "";
  assert.doesNotMatch(joinSnippet, /--json/);
  assert.ok(markdown.includes("[A-Za-z0-9_][A-Za-z0-9_-]{7,127}"));
  assert.match(markdown, /one-time join/i);
  assert.match(markdown, /do not write it to a file or recurring task/i);
  assert.match(markdown, /member capability remains private/i);
  assert.match(markdown, /prompt, recurring task, browser, log, repository, or command argument/i);
  assert.match(markdown, /private.*no-money proof/i);
  assert.doesNotMatch(markdown, /Team key/i);
  assert.match(markdown, /profile/);
  assert.match(markdown, /team ads browse/);
  assert.match(markdown, /team ads send/);
  assert.match(markdown, /no cash value/i);
  assert.match(markdown, /AD DADDY: <sponsor message>/);
  assert.match(markdown, /ad-daddy team join/);
  assert.match(markdown, /ad-daddy team actions/);
  assert.match(markdown, /packages\/ad-daddy-skill/);
  assert.match(markdown, /team profile show/);
  assert.match(markdown, /team advertiser show/);
  assert.match(markdown, /team people list/);
  assert.match(markdown, /team ads send/);
  assert.match(markdown, /team receiver setup/);
  assert.match(markdown, /--cadence <MINUTES>/);
  assert.match(markdown, /Turn on sponsored task checks every <MINUTES> minutes and accept <TERMS_VERSION> and <PRIVACY_VERSION>\?/);
  assert.match(markdown, /team receiver setup --confirm/);
  assert.doesNotMatch(markdown, /accept-disclosure|accept-terms|accept-privacy/);
  assert.match(markdown, /wants to get ads in Codex/);
  assert.match(markdown, /Other hosts retain all profile and advertiser actions/);
  assert.match(markdown, /one combined confirmation/i);
  assert.match(markdown, /resumes the stated frequency and explicitly accepts both returned terms\/privacy versions by name/i);
  assert.match(markdown, /Build my profile/);
  assert.match(markdown, /Get ads/);
  assert.match(markdown, /Send an ad/);
  assert.match(markdown, /current authorized workspace/);
  assert.match(markdown, /receiver profile.*advertiser profile/i);
  assert.match(markdown, /exact public fields.*before saving or sending anything/i);
  assert.match(markdown, /team check/);
  assert.match(markdown, /browser is optional/i);
  assert.doesNotMatch(markdown, /Existing member token/);
  assert.doesNotMatch(markdown, /paste.*token/i);
  assert.doesNotMatch(markdown, /localhost/);
});
